FROM mysql:8.0.34

EXPOSE 3306

ENV MYSQL_ROOT_PASSWORD=admin \
    MYSQL_DATABASE=app \
    MYSQL_USER=admin \
    MYSQL_PASSWORD=admin

COPY ./scripts/ /docker-entrypoint-initdb.d/
COPY my.cnf /etc/mysql/conf.d/